//
// Created by matxin on 16/09/23.
//

#ifndef SCIENTIFICCOMPUTING_ROUND_INTEGER_H
#define SCIENTIFICCOMPUTING_ROUND_INTEGER_H

#endif //SCIENTIFICCOMPUTING_ROUND_INTEGER_H

int round_integer(double a);